## SQL at Scale with Spark SQL

Welcome to the SQL mini project. For this project, you will use the Databricks Platform and work through a series of exercises using Spark SQL. The dataset size may not be too big but the intent here is to familiarize yourself with the Spark SQL interface which scales easily to huge datasets, without you having to worry about changing your SQL queries. 

The data you need is present in the mini-project folder in the form of three CSV files. This data will be imported in Databricks to create the following tables under the __`country_club`__ database.

<br>
1. The __`bookings`__ table,
2. The __`facilities`__ table, and
3. The __`members`__ table.

You will be uploading these datasets shortly into the Databricks platform to understand how to create a database within minutes! Once the database and the tables are populated, you will be focusing on the mini-project questions.

In the mini project, you'll be asked a series of questions. You can solve them using the databricks platform, but for the final deliverable,
please download this notebook as an IPython notebook (__`File -> Export -> IPython Notebook`__) and upload it to your GitHub.

### Creating the Database

We will first create our database in which we will be creating our three tables of interest

In [0]:
%sql 
drop database if exists country_club cascade;
create database country_club;
show databases;

namespace
country_club
default

### Creating the Tables

In this section, we will be creating the three tables of interest and populate them with the data from the CSV files already available to you. 
To get started, first upload the three CSV files to the DBFS as depicted in the following figure

![](https://i.imgur.com/QcCruBr.png)


Once you have done this, please remember to execute the following code to build the dataframes which will be saved as tables in our database

In [0]:
# File location and type
file_location_bookings = "/FileStore/tables/Bookings.csv"
file_location_facilities = "/FileStore/tables/Facilities.csv"
file_location_members = "/FileStore/tables/Members.csv"

file_type = "csv"

# CSV options
infer_schema = "true"
first_row_is_header = "true"
delimiter = ","

# The applied options are for CSV files. For other file types, these will be ignored.
bookings_df = (spark.read.format(file_type) 
                    .option("inferSchema", infer_schema) 
                    .option("header", first_row_is_header) 
                    .option("sep", delimiter) 
                    .load(file_location_bookings))

facilities_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_facilities))

members_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_members))

### Viewing the dataframe schemas

We can take a look at the schemas of our potential tables to be written to our database soon

In [0]:
print('Bookings Schema')
bookings_df.printSchema()
print('Facilities Schema')
facilities_df.printSchema()
print('Members Schema')
members_df.printSchema()

### Create permanent tables
We will be creating three permanent tables here in our __`country_club`__ database as we discussed previously with the following code

In [0]:
permanent_table_name_bookings = "country_club.Bookings"
bookings_df.write.format("parquet").saveAsTable(permanent_table_name_bookings)

permanent_table_name_facilities = "country_club.Facilities"
facilities_df.write.format("parquet").saveAsTable(permanent_table_name_facilities)

permanent_table_name_members = "country_club.Members"
members_df.write.format("parquet").saveAsTable(permanent_table_name_members)

### Refresh tables and check them

In [0]:
%sql
use country_club;
REFRESH table bookings;
REFRESH table facilities;
REFRESH table members;
show tables;

database,tableName,isTemporary
country_club,bookings,false
country_club,facilities,false
country_club,members,false

### Test a sample SQL query

__Note:__ You can use __`%sql`__ at the beginning of a cell and write SQL queries directly as seen in the following cell. Neat isn't it!

In [0]:
%sql
select * from bookings limit 3

bookid,facid,memid,starttime,slots
0,3,1,2012-07-03 11:00:00,2
1,4,1,2012-07-03 08:00:00,2
2,6,0,2012-07-03 18:00:00,2

#### Q1: Some of the facilities charge a fee to members, but some do not. Please list the names of the facilities that do.

In [0]:
%sql
select * from facilities where `membercost` >0

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,Tennis Court 1,5.0,25.0,10000,200
1,Tennis Court 2,5.0,25.0,8000,200
4,Massage Room 1,9.9,80.0,4000,3000
5,Massage Room 2,9.9,80.0,4000,3000
6,Squash Court,3.5,17.5,5000,80

####  Q2: How many facilities do not charge a fee to members?

In [0]:
%sql
select * from facilities where `membercost` = 0

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
2,Badminton Court,0.0,15.5,4000,50
3,Table Tennis,0.0,5.0,320,10
7,Snooker Table,0.0,5.0,450,15
8,Pool Table,0.0,5.0,400,15

#### Q3: How can you produce a list of facilities that charge a fee to members, where the fee is less than 20% of the facility's monthly maintenance cost? 
#### Return the facid, facility name, member cost, and monthly maintenance of the facilities in question.

In [0]:
%sql
select * from facilities where  (`membercost` < (`monthlymaintenance` * 0.2))

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,Tennis Court 1,5.0,25.0,10000,200
1,Tennis Court 2,5.0,25.0,8000,200
2,Badminton Court,0.0,15.5,4000,50
3,Table Tennis,0.0,5.0,320,10
4,Massage Room 1,9.9,80.0,4000,3000
5,Massage Room 2,9.9,80.0,4000,3000
6,Squash Court,3.5,17.5,5000,80
7,Snooker Table,0.0,5.0,450,15
8,Pool Table,0.0,5.0,400,15

#### Q4: How can you retrieve the details of facilities with ID 1 and 5? Write the query without using the OR operator.

In [0]:
%sql
select * from facilities where (`facid` = 1 or `facid` = 5)

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
1,Tennis Court 2,5.0,25.0,8000,200
5,Massage Room 2,9.9,80.0,4000,3000

#### Q5: How can you produce a list of facilities, with each labelled as 'cheap' or 'expensive', depending on if their monthly maintenance cost is more than $100? 
#### Return the name and monthly maintenance of the facilities in question.

In [0]:
%sql
select (case when monthlymaintenance > 100 then 'expensive' else 'cheap' end) as label, facilities.monthlymaintenance, facilities.name from facilities

label,monthlymaintenance,name
expensive,200,Tennis Court 1
expensive,200,Tennis Court 2
cheap,50,Badminton Court
cheap,10,Table Tennis
expensive,3000,Massage Room 1
expensive,3000,Massage Room 2
cheap,80,Squash Court
cheap,15,Snooker Table
cheap,15,Pool Table

#### Q6: You'd like to get the first and last name of the last member(s) who signed up. Do not use the LIMIT clause for your solution.

In [0]:
%sql
SELECT members.firstname, members.surname, members.joindate  FROM members WHERE members.joindate = (SELECT MAX(members.joindate) FROM members)

firstname,surname,joindate
Darren,Smith,2012-09-26 18:08:45

####  Q7: How can you produce a list of all members who have used a tennis court?
- Include in your output the name of the court, and the name of the member formatted as a single column. 
- Ensure no duplicate data
- Also order by the member name.

In [0]:
%sql
select DISTINCT members.firstname, facilities.name from members, facilities, bookings where members.firstname != 'GUEST' and members.memid = bookings.memid and facilities.facid = bookings.facid and facilities.name LIKE 'Tennis Court%'

firstname,name
Jemima,Tennis Court 1
Anne,Tennis Court 2
David,Tennis Court 1
Tim,Tennis Court 1
Janice,Tennis Court 1
Matthew,Tennis Court 1
Ponder,Tennis Court 1
Darren,Tennis Court 2
Jack,Tennis Court 1
Florence,Tennis Court 1
Douglas,Tennis Court 1
Charles,Tennis Court 2
Ramnaresh,Tennis Court 2
Erica,Tennis Court 1
Anne,Tennis Court 1
Jack,Tennis Court 2
Millicent,Tennis Court 2
Janice,Tennis Court 2
Charles,Tennis Court 1
John,Tennis Court 1
Tim,Tennis Court 2
Joan,Tennis Court 1
Tracy,Tennis Court 2
Nancy,Tennis Court 2
Henrietta,Tennis Court 2
Gerald,Tennis Court 2
Jemima,Tennis Court 2
John,Tennis Court 2
Burton,Tennis Court 1
Burton,Tennis Court 2
Ramnaresh,Tennis Court 1
Timothy,Tennis Court 2
Timothy,Tennis Court 1
David,Tennis Court 2
Florence,Tennis Court 2
Nancy,Tennis Court 1
Ponder,Tennis Court 2
Gerald,Tennis Court 1
Tracy,Tennis Court 1

#### Q8: How can you produce a list of bookings on the day of 2012-09-14 which will cost the member (or guest) more than $30? 

- Remember that guests have different costs to members (the listed costs are per half-hour 'slot')
- The guest user's ID is always 0. 

#### Include in your output the name of the facility, the name of the member formatted as a single column, and the cost.

- Order by descending cost, and do not use any subqueries.

In [0]:
%sql
select CONCAT(members.firstname,members.surname,'@',facilities.name) as fullname, Sum(case when members.firstname = 'GUEST' then facilities.guestcost * bookings.slots *2 else facilities.membercost * bookings.slots *2 end) as TotalCost from members, bookings, facilities where members.memid = bookings.memid and facilities.facid = bookings.facid AND (bookings.starttime > '2012-09-15' and bookings.starttime < '2012-09-16') GROUP BY fullname HAVING Sum(case when members.firstname = 'GUEST' then facilities.guestcost * bookings.slots*2 else facilities.membercost * bookings.slots*2 end) >30

fullname,TotalCost
RamnareshSarwin@Tennis Court 2,60.0
GUESTGUEST@Massage Room 1,1600.0
JackSmith@Massage Room 1,39.6
GUESTGUEST@Massage Room 2,320.0
RamnareshSarwin@Massage Room 1,39.6
GUESTGUEST@Squash Court,350.0
TimRownam@Massage Room 1,39.6
GUESTGUEST@Badminton Court,279.0
GUESTGUEST@Tennis Court 1,600.0
DavidPinker@Massage Room 1,39.6
JemimaFarrell@Massage Room 1,39.6
TimothyBaker@Massage Room 1,79.2

#### Q9: This time, produce the same result as in Q8, but using a subquery.

In [0]:
%sql
select members.firstname from members, bookings, facilities where members.memid = bookings.memid and bookings.starttime = '2012-09-14' and facilities.facid = bookings.facid and `membercost` > 30

#### Q10: Produce a list of facilities with a total revenue less than 1000.
- The output should have facility name and total revenue, sorted by revenue. 
- Remember that there's a different cost for guests and members!

In [0]:
%sql
select Sum(case when members.firstname = 'GUEST' then facilities.guestcost else facilities.membercost end) as TotalCost, facilities.facid from facilities, members, bookings where facilities.facid = bookings.facid and members.memid = bookings.memid  GROUP BY facilities.facid HAVING (Sum(case when members.firstname = 'GUEST' then facilities.guestcost else facilities.membercost end) < 1000) order by TotalCost;

TotalCost,facid
90.0,3
115.0,7
265.0,8
604.5,2